// <auto-generated />
using ApiBilanClubDegre.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiBilanClubDegre.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiBilanClubDegre.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question10")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question11")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question12")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question13")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question14")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question15")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question16")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question17")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question18")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question19")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question20")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question21")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question22")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question23")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question24")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question25")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question26")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question27")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question28")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question29")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question30")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question7")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question8")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question9")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
